[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth-:splat"
  status = 200

[[redirects]]
  from = "/api/videos/*"
  to = "/.netlify/functions/videos-:splat"
  status = 200

[[redirects]]
  from = "/api/settings/*"
  to = "/.netlify/functions/settings-:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200