# Railway Deployment Configuration
# This file helps Railway understand your project structure

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environment]
  NODE_ENV = "production"
  # Railway will auto-assign PORT, don't set it manually